spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lab_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '@Lyh20040816'


  data:
    redis:
      host: 127.0.0.1
      port: 6379
      # password: 你的Redis密码（如果没有设置密码，保持注释或删除该行）

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: helloserver2026secretkeyabcdefghijklmnopqrstuvwxyz0123456789ABCDEF
  expiration: 3600000