spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lab_db
    username: postgres
    password: 123456

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      # password: 你的Redis密码（如果没有设置密码，保持注释或删除该行）

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl